I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 179, in script call
    call start2 from script2
  File "game/script2.rpy", line 357, in script
    "You tune the lecture out as you think about the fun Manga you started last night. The story was far more interesting than whatever the teacher is talking about.":
  File "game/script2.rpy", line 357, in <module>
    "You tune the lecture out as you think about the fun Manga you started last night. The story was far more interesting than whatever the teacher is talking about.":
NameError: name 'intel' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 179, in script call
    call start2 from script2
  File "game/script2.rpy", line 357, in script
    "You tune the lecture out as you think about the fun Manga you started last night. The story was far more interesting than whatever the teacher is talking about.":
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script2.rpy", line 357, in <module>
    "You tune the lecture out as you think about the fun Manga you started last night. The story was far more interesting than whatever the teacher is talking about.":
NameError: name 'intel' is not defined

Darwin-19.6.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
MythJam2020 1.0
Sat Oct 10 21:09:53 2020
